// File: switch.v
// Generated by MyHDL 0.11
// Date: Sat Jan  9 17:29:07 2021


`timescale 1ns/10ps

module switch (
    i_sw,
    o_led
);


input i_sw;
output o_led;
wire o_led;





assign o_led = i_sw;

endmodule
