// File: addrbump.v
// Generated by MyHDL 0.11
// Date: Fri Dec 18 17:55:44 2020


`timescale 1ns/10ps

module addrbump (
    addrtoinc,
    update2_i,
    clk,
    incaddr,
    update2_o
);


input [4:0] addrtoinc;
input update2_i;
input clk;
output [4:0] incaddr;
reg [4:0] incaddr;
output update2_o;
reg update2_o;




always @(posedge clk) begin: ADDRBUMP_RTL4
    if ((update2_i == 1)) begin
        update2_o <= 0;
        incaddr <= (addrtoinc + 1);
    end
    else begin
        update2_o <= 1;
    end
end

endmodule
