// File: oneminuszero.v
// Generated by MyHDL 0.11
// Date: Thu Dec 24 09:55:39 2020


`timescale 1ns/10ps

module oneminuszero (
    first_i,
    nd_i,
    update1_i,
    clk,
    sub_o,
    update1_o
);


input signed [15:0] first_i;
input signed [15:0] nd_i;
input update1_i;
input clk;
output signed [15:0] sub_o;
reg signed [15:0] sub_o;
output update1_o;
reg update1_o;




always @(posedge clk) begin: ONEMINUSZERO_RTL1
    if ((update1_i == 1)) begin
        update1_o <= 0;
        sub_o <= (first_i - nd_i);
    end
    else begin
        update1_o <= 1;
    end
end

endmodule
