// File: ram.v
// Generated by MyHDL 0.11
// Date: Mon Dec 14 11:02:47 2020


`timescale 1ns/10ps

module ram (
    dout,
    din,
    addr,
    we,
    clk
);
// Ram model 

output signed [15:0] dout;
wire signed [15:0] dout;
input signed [15:0] din;
input [9:0] addr;
input we;
input clk;

reg [14:0] mem [0:1024-1];



always @(posedge clk) begin: RAM_WRITE
    if (we) begin
        mem[addr] <= din;
    end
end



assign dout = mem[addr];

endmodule
