// File: ram.v
// Generated by MyHDL 0.11
// Date: Thu Dec 24 10:25:24 2020


`timescale 1ns/10ps

module ram (
    dout,
    din,
    addr,
    we,
    clk
);
// Ram model 

output signed [15:0] dout;
wire signed [15:0] dout;
input signed [15:0] din;
input [4:0] addr;
input we;
input clk;

reg signed [15:0] mem [0:32-1];



always @(posedge clk) begin: RAM_WRITE
    if (we) begin
        mem[addr] <= din;
    end
end



assign dout = mem[addr];

endmodule
