// File: rs232loopback.v
// Generated by MyHDL 0.11
// Date: Thu Jan 14 17:59:20 2021


`timescale 1ns/10ps

module rs232loopback (
    clock,
    iRX,
    oTX
);


input clock;
output iRX;
reg iRX;
input oTX;




always @(posedge clock) begin: RS232LOOPBACK_LOGIC
    iRX <= oTX;
end

endmodule
