// File: rs232loopback.v
// Generated by MyHDL 0.11
// Date: Wed Dec 30 16:38:22 2020


`timescale 1ns/10ps

module rs232loopback (
    oTX,
    iRX
);


input oTX;
output iRX;
wire iRX;





assign iRX = oTX;

endmodule
