// File: pwruprst.v
// Generated by MyHDL 0.11
// Date: Thu Jan 21 17:18:19 2021


`timescale 1ns/10ps

module pwruprst (
    iClk,
    iRst,
    pwrup
);


input iClk;
output iRst;
reg iRst;
output [5:0] pwrup;
reg [5:0] pwrup;




always @(posedge iClk) begin: PWRUPRST_LOGIC2
    if (((iRst == 1) && (pwrup == 40))) begin
        iRst <= 0;
    end
    else begin
        if ((pwrup <= 60)) begin
            pwrup <= (pwrup + 1);
        end
    end
    if ((pwrup == 60)) begin
        iRst <= 1;
    end
end

endmodule
