// File: rom.v
// Generated by MyHDL 0.11
// Date: Thu Feb  4 16:09:04 2021


`timescale 1ns/10ps

module rom (
    rom_dout,
    rom_addr
);


output [7:0] rom_dout;
reg [7:0] rom_dout;
input [3:0] rom_addr;




always @(rom_addr) begin: ROM_READ
    case (rom_addr)
        0: rom_dout = 72;
        1: rom_dout = 69;
        2: rom_dout = 76;
        3: rom_dout = 76;
        4: rom_dout = 79;
        5: rom_dout = 87;
        6: rom_dout = 79;
        7: rom_dout = 82;
        8: rom_dout = 76;
        9: rom_dout = 68;
        10: rom_dout = 13;
        default: rom_dout = 10;
    endcase
end

endmodule
