// File: fifo.v
// Generated by MyHDL 0.11
// Date: Wed Nov 18 18:19:01 2020


`timescale 1ns/10ps

module fifo (
    clk,
    empty_r,
    full_r,
    enr_r,
    enw_r,
    dataout_r,
    datain_r
);
// The following between the single quotes ':= "0000"' needs to added to line below
// signal instance_1_reset_ctn: unsigned(3 downto 0);
// before the ';' to be like the following
// signal instance_1_reset_ctn: unsigned(3 downto 0):= "0000";
//  

input clk;
output empty_r;
reg empty_r;
output full_r;
reg full_r;
input enr_r;
input enw_r;
output [8:0] dataout_r;
reg [8:0] dataout_r;
input [8:0] datain_r;

reg [3:0] reset_ctn;
reg [7:0] readptr;
reg [7:0] writeptr;
reg [8:0] mem [0:256-1];



always @(posedge clk) begin: FIFO_RTL
    if ((reset_ctn < 10)) begin
        readptr <= 0;
        writeptr <= 0;
        reset_ctn <= (reset_ctn + 1);
    end
    if ((enr_r == 1'b1)) begin
        dataout_r <= mem[readptr];
        if (($signed({1'b0, readptr}) < ((2 ** 8) - 1))) begin
            readptr <= (readptr + 1);
        end
    end
    if ((enw_r == 1'b1)) begin
        mem[writeptr] <= datain_r;
        if (($signed({1'b0, writeptr}) <= ((2 ** 8) - 1))) begin
            writeptr <= (writeptr + 1);
        end
    end
    if (($signed({1'b0, readptr}) == ((2 ** 8) - 1))) begin
        readptr <= 0;
    end
    if (($signed({1'b0, writeptr}) == ((2 ** 8) - 1))) begin
        full_r <= 1'b1;
        writeptr <= 0;
    end
    else begin
        full_r <= 1'b0;
    end
    if ((writeptr == 0)) begin
        empty_r <= 1'b1;
    end
    else begin
        empty_r <= 1'b0;
    end
end

endmodule
