// File: Odd_Even_Fsm.v
// Generated by MyHDL 0.11
// Date: Wed Nov 18 18:06:56 2020


`timescale 1ns/10ps

module Odd_Even_Fsm (
    state,
    clk,
    rst_fsm,
    addr_left,
    muxsel_i,
    addr_sam,
    addr_rht,
    muxaddrsel,
    we_1,
    dout,
    left_i,
    sam_i,
    right_i,
    do_first,
    x,
    z,
    flgs_i,
    update_i,
    res_o,
    update_o,
    end_of_col,
    addr_in,
    xfifo,
    enr_r,
    enw_r,
    del_ctn
);


output [27:0] state;
reg [27:0] state;
input clk;
input rst_fsm;
output [7:0] addr_left;
reg [7:0] addr_left;
output muxsel_i;
reg muxsel_i;
output [7:0] addr_sam;
reg [7:0] addr_sam;
output [7:0] addr_rht;
reg [7:0] addr_rht;
output [1:0] muxaddrsel;
reg [1:0] muxaddrsel;
output we_1;
reg we_1;
input [8:0] dout;
output [8:0] left_i;
reg [8:0] left_i;
output [8:0] sam_i;
reg [8:0] sam_i;
output [8:0] right_i;
reg [8:0] right_i;
output do_first;
reg do_first;
output signed [9:0] x;
reg signed [9:0] x;
input [8:0] z;
output [3:0] flgs_i;
reg [3:0] flgs_i;
output update_i;
reg update_i;
input signed [9:0] res_o;
input update_o;
output end_of_col;
reg end_of_col;
output [7:0] addr_in;
reg [7:0] addr_in;
output signed [9:0] xfifo;
reg signed [9:0] xfifo;
output enr_r;
reg enr_r;
input enw_r;
output [7:0] del_ctn;
reg [7:0] del_ctn;

reg we_in;
wire [14:0] dataout_r;

assign dataout_r = 15'd0;


always @(posedge clk, negedge rst_fsm) begin: ODD_EVEN_FSM_FSM
    if ((rst_fsm == 1'b0)) begin
        addr_left <= 0;
        addr_sam <= 1;
        addr_rht <= 2;
        do_first <= 0;
        flgs_i <= 7;
        end_of_col <= 0;
        addr_in <= 0;
        state <= 28'b0000000000000000000000000001;
    end
    else begin
        casez (state)
            28'b???????????????????????????1: begin
                we_in <= 1;
                muxsel_i <= 1;
                enr_r <= 1;
                state <= 28'b0000000000100000000000000000;
            end
            28'b??????????????????????????1?: begin
                if ((muxsel_i == 0)) begin
                    if ((addr_left < 254)) begin
                        if (((addr_left == 0) && (do_first == 0))) begin
                            // do_first goes hi to execute first location
                            addr_left <= 0;
                            muxaddrsel <= 0;
                            we_1 <= 0;
                            state <= 28'b0000000000000000000000010000;
                        end
                        else begin
                            addr_left <= (addr_left + 2);
                            muxaddrsel <= 0;
                            we_1 <= 0;
                            state <= 28'b0000000000000000000000010000;
                        end
                    end
                end
            end
            default: begin
                if ((state == 28'b0000000000000000000000000100)) begin
                    if ((addr_sam < 254)) begin
                        if (((addr_sam == 1) && (do_first == 0))) begin
                            addr_sam <= 1;
                            muxaddrsel <= 1;
                            we_1 <= 0;
                            state <= 28'b0000000000000000000000100000;
                        end
                        else begin
                            addr_sam <= (addr_sam + 2);
                            muxaddrsel <= 1;
                            we_1 <= 0;
                            state <= 28'b0000000000000000000000100000;
                        end
                    end
                end
                else begin
                    casez (state)
                        28'b????????????????????????1???: begin
                            if ((muxsel_i == 0)) begin
                                if ((addr_rht < 254)) begin
                                    if (((addr_rht == 2) && (do_first == 0))) begin
                                        do_first <= 1;
                                        addr_rht <= 2;
                                        muxaddrsel <= 2;
                                        we_1 <= 0;
                                        state <= 28'b0000000000000000000001000000;
                                    end
                                    else begin
                                        addr_rht <= (addr_rht + 2);
                                        muxaddrsel <= 2;
                                        we_1 <= 0;
                                        state <= 28'b0000000000000000000001000000;
                                    end
                                end
                                else begin
                                    addr_left <= 1;
                                    addr_sam <= 2;
                                    addr_rht <= 3;
                                    do_first <= 0;
                                    flgs_i <= 6;
                                    state <= 28'b0000000000000100000000000000;
                                end
                            end
                        end
                        28'b?????????????1??????????????: begin
                            if ((muxsel_i == 0)) begin
                                if ((addr_left < 254)) begin
                                    if (((addr_left == 1) && (do_first == 0))) begin
                                        // do_first goes hi to execute first location
                                        addr_left <= 1;
                                        muxaddrsel <= 0;
                                        we_1 <= 0;
                                        state <= 28'b0000000000000000000000010000;
                                    end
                                    else begin
                                        addr_left <= (addr_left + 2);
                                        muxaddrsel <= 0;
                                        we_1 <= 0;
                                        state <= 28'b0000000000000000000000010000;
                                    end
                                end
                            end
                        end
                        default: begin
                            if ((state == 28'b0000000000001000000000000000)) begin
                                if ((addr_sam < 254)) begin
                                    if (((addr_sam == 2) && (do_first == 0))) begin
                                        addr_sam <= 2;
                                        muxaddrsel <= 1;
                                        we_1 <= 0;
                                        state <= 28'b0000000000000000000000100000;
                                    end
                                    else begin
                                        addr_sam <= (addr_sam + 2);
                                        muxaddrsel <= 1;
                                        we_1 <= 0;
                                        state <= 28'b0000000000000000000000100000;
                                    end
                                end
                                else begin
                                    addr_left <= 1;
                                    addr_sam <= 2;
                                    addr_rht <= 3;
                                    state <= 28'b1000000000000000000000000000;
                                end
                            end
                            else begin
                                casez (state)
                                    28'b???????????1????????????????: begin
                                        if ((muxsel_i == 0)) begin
                                            if ((addr_rht < 254)) begin
                                                if (((addr_rht == 3) && (do_first == 0))) begin
                                                    do_first <= 1;
                                                    addr_rht <= 3;
                                                    muxaddrsel <= 2;
                                                    we_1 <= 0;
                                                    state <= 28'b0000000000000000000001000000;
                                                end
                                                else begin
                                                    addr_rht <= (addr_rht + 2);
                                                    muxaddrsel <= 2;
                                                    we_1 <= 0;
                                                    state <= 28'b0000000000000000000001000000;
                                                end
                                            end
                                            else begin
                                                addr_left <= 1;
                                                addr_sam <= 2;
                                                addr_rht <= 3;
                                                state <= 28'b1000000000000000000000000000;
                                            end
                                        end
                                    end
                                    28'b1???????????????????????????: begin
                                        end_of_col <= 1;
                                        state <= 28'b1000000000000000000000000000;
                                    end
                                    28'b???????????????????????1????: begin
                                        left_i <= dout;
                                        if ((flgs_i == 6)) begin
                                            state <= 28'b0000000000001000000000000000;
                                        end
                                        else begin
                                            state <= 28'b0000000000000000000000000100;
                                        end
                                    end
                                    28'b??????????????????????1?????: begin
                                        sam_i <= dout;
                                        if ((flgs_i == 6)) begin
                                            state <= 28'b0000000000010000000000000000;
                                        end
                                        else begin
                                            state <= 28'b0000000000000000000000001000;
                                        end
                                    end
                                    28'b?????????????????????1??????: begin
                                        right_i <= dout;
                                        state <= 28'b0000000000000000000010000000;
                                    end
                                    28'b????????????????????1???????: begin
                                        // setting addr to sam
                                        update_i <= 1;
                                        we_1 <= 1;
                                        muxaddrsel <= 1;
                                        state <= 28'b0000000000000000000100000000;
                                    end
                                    default: begin
                                        if ((state == 28'b0000000000000000000100000000)) begin
                                            muxaddrsel <= 1;
                                            state <= 28'b0000000000000000001000000000;
                                        end
                                        else begin
                                            casez (state)
                                                28'b??????????????????1?????????: begin
                                                    muxaddrsel <= 1;
                                                    x <= res_o[9-1:0];
                                                    state <= 28'b0000000000000000010000000000;
                                                end
                                                28'b?????????????????1??????????: begin
                                                    muxaddrsel <= 1;
                                                    update_i <= 0;
                                                    state <= 28'b0000000000000000100000000000;
                                                end
                                                28'b????????????????1???????????: begin
                                                    muxaddrsel <= 1;
                                                    state <= 28'b0000000000000001000000000000;
                                                end
                                                28'b???????????????1????????????: begin
                                                    muxaddrsel <= 1;
                                                    state <= 28'b0000000000000010000000000000;
                                                end
                                                28'b??????????????1?????????????: begin
                                                    muxaddrsel <= 1;
                                                    we_1 <= 0;
                                                    state <= 28'b0000000000000000000000000010;
                                                end
                                                28'b??????????1?????????????????: begin
                                                    del_ctn <= 0;
                                                    if ((addr_in <= 254)) begin
                                                        enr_r <= 0;
                                                        state <= 28'b0000000001000000000000000000;
                                                    end
                                                    else begin
                                                        muxsel_i <= 0;
                                                        enr_r <= 0;
                                                        we_in <= 0;
                                                        state <= 28'b0000000000000000000000000010;
                                                    end
                                                end
                                                default: begin
                                                    casez (state)
                                                        28'b?????????1??????????????????: begin
                                                            xfifo <= dataout_r[9-1:0];
                                                            state <= 28'b0000000010000000000000000000;
                                                        end
                                                        28'b????????1???????????????????: begin
                                                            if ((del_ctn < 2)) begin
                                                                del_ctn <= (del_ctn + 1);
                                                            end
                                                            else begin
                                                                state <= 28'b0010000000000000000000000000;
                                                            end
                                                        end
                                                        28'b???????1????????????????????: begin
                                                            state <= 28'b0000001000000000000000000000;
                                                        end
                                                        28'b??????1?????????????????????: begin
                                                            state <= 28'b0000010000000000000000000000;
                                                        end
                                                        28'b?????1??????????????????????: begin
                                                            state <= 28'b0000100000000000000000000000;
                                                        end
                                                        28'b????1???????????????????????: begin
                                                            state <= 28'b0001000000000000000000000000;
                                                        end
                                                        28'b???1????????????????????????: begin
                                                            state <= 28'b0010000000000000000000000000;
                                                        end
                                                        28'b??1?????????????????????????: begin
                                                            enr_r <= 1;
                                                            state <= 28'b0100000000000000000000000000;
                                                        end
                                                        28'b?1??????????????????????????: begin
                                                            addr_in <= (addr_in + 1);
                                                            state <= 28'b0000000000100000000000000000;
                                                        end
                                                        default: begin
                                                            $finish;
                                                        end
                                                    endcase
                                                end
                                            endcase
                                        end
                                    end
                                endcase
                            end
                        end
                    endcase
                end
            end
        endcase
    end
end

endmodule
