// File: ram.v
// Generated by MyHDL 0.11
// Date: Tue Nov 17 15:58:07 2020


`timescale 1ns/10ps

module ram (
    dout,
    din,
    addr,
    we,
    clk
);
// Ram model 

output [14:0] dout;
wire [14:0] dout;
input [14:0] din;
input [7:0] addr;
input we;
input clk;

reg [14:0] mem [0:256-1];



always @(posedge clk) begin: RAM_WRITE
    if (we) begin
        mem[addr] <= din;
    end
end



assign dout = mem[addr];

endmodule
