// File: signed2twoscomplement.v
// Generated by MyHDL 0.11
// Date: Wed Nov 18 18:08:27 2020


`timescale 1ns/10ps

module signed2twoscomplement (
    clk,
    x,
    z
);


input clk;
input signed [9:0] x;
output [8:0] z;
reg [8:0] z;




always @(posedge clk) begin: SIGNED2TWOSCOMPLEMENT_UNSIGNED_LOGIC
    z <= x;
end

endmodule
